stages:
  - setup
  - build
  - test
  - deploy
# Cache client/node_modules between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  untracked: true
  paths:
    - client/node_modules/
setup:
  stage: setup
  script:
    - cd client
    - npm ci
    - cd ..
    - cd server
    - dotnet restore
build:
  stage: build
  script:
    - cd client
    - npm run lint
    - npm run build
    - cd ..
    - cd server
    - dotnet build
    - cd ..
test:
  stage: test
  script:
    - cd server/test/GisHub.Test
    - dotnet test
    - cd ..
deploy:
  stage: deploy
  environment:
    name: staging
  only:
    - master
  script:
    - cd docker
    - ./build-docker-images.sh
    - ./deploy-images.sh
