stages:
  - setup
  - build
  - test
  - deploy
# Cache client/node_modules between jobs
setup:
  stage: setup
  script:
    - dotnet restore
build:
  stage: build
  script:
    - dotnet build
test:
  stage: test
  script:
    - cd test/Test
    - dotnet test
    - cd ..
deploy:
  stage: deploy
  environment:
    name: staging
  only:
    - master
  script:
    - cd docker
    - ./build-docker-images.sh
    - ./deploy-images.sh
