services:
  app:
    image: beginor/net-core-app
    ports:
      - 8080:8080
    volumes:
      - ./config:/app/config
      - ./log:/app/log
      - ./cache:/app/cache
    environment:
      TZ: Asia/Shanghai
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_PATHBASE: /net-core-app
    restart: unless-stopped
networks:
  default:
    external: true
    name: compose
