version: "3.9"
services:
  gishub:
    image: beginor/gishub
    hostname: gishub
    ports:
      - 5000:5000
    volumes:
      - ./config:/gishub/config
      - ./log:/gishub/log
      - ./data:/gishub_data
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_PATHBASE: /gishub
    restart: unless-stopped
networks:
  default:
    external: true
    name: compose
