version: "3"
services:
  gishub:
    image: beginor/gishub
    hostname: gishub
    ports:
      - 5000:80
    volumes:
      - ./log:/gishub/log
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    restart: unless-stopped
networks:
  default:
    external:
      name: compose
